# Generated by Django 4.1.7 on 2023-04-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserMistakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25)),
                ('sentence', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.dictionary')),
            ],
        ),
    ]
