# Generated by Django 4.1.7 on 2023-04-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMistakes',
        ),
    ]
