# Generated by Django 4.1.7 on 2023-05-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_usermistakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='sentence',
            field=models.CharField(max_length=300),
        ),
    ]
