# Generated by Django 4.1.7 on 2023-05-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_progdictionary_alter_dictionary_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=300)),
            ],
        ),
    ]
