# Generated by Django 4.1.7 on 2023-05-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tvdictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=300)),
            ],
        ),
    ]
